Feature/change ui native
RUTILEA/SDTest pull request #15
Opened 2019-06-03 09:31 UTC by akshuga

Fixes 23(開発ロードマップ)

## Proposed Changes

  - ボタンをnativeに変更
  - resourceフォルダの作成, assetsフォルダの削除

2019-06-03 15:34 UTC, jrsaruo commented
@akshuga 
起動画面のボタンだけはカスタムデザインにしませんか？

2019-06-03 17:14 UTC, akshuga commented
大嶋さんからは, 起動画面もネイティヴUIでということでした

2019-06-03 19:10 UTC, dryout commented
一旦はすべてネイティブにしようということだったと思います！

2019-06-03 19:43 UTC, akshuga commented
qrcファイルをresource/base/qrcに移し, パスを更新しなおしました.
これ以降はqrcは触らなくても大丈夫そうです

2019-06-04 10:03 UTC, jrsaruo requested changes

2019-06-04 10:03 UTC, jrsaruo commented on src/main/python/view/ui/inspection.py
> +        self.result.setCurrentIndex(1)
@akshuga 
currentIndexが変更されているので0に戻してもらえると！

2019-06-04 12:24 UTC, akshuga commented
起動画面のみボタンをカスタムにしました

2019-06-04 12:37 UTC, jrsaruo commented
@akshuga 
runしたらicon_rcモジュールがないって怒られるんですが、佐藤さんの環境だと動いてますか？
```
Traceback (most recent call last):
  File "/Users/Yusaku/Development/RUTILEA/SDTest/src/main/python/main.py", line 3, in <module>
    from view.startup import StartupWidget
  File "/Users/Yusaku/Development/RUTILEA/SDTest/src/main/python/view/startup.py", line 1, in <module>
    ﻿from view.ui.startup import Ui_StartupWidget
  File "/Users/Yusaku/Development/RUTILEA/SDTest/src/main/python/view/ui/startup.py", line 173, in <module>
    import icon_rc
ModuleNotFoundError: No module named 'icon_rc'
```

2019-06-04 16:42 UTC, akshuga commented
失礼しました！ qrcファイルの場所を修正しました.
それに伴い, qrcから_rc.pyへの変換を
`pyrcc5 --import-from qrc -o FILENAME_rc.py FILENAME.qrc`
に変更したいです(Readme変更しときます)

2019-06-05 09:17 UTC, jrsaruo commented
@akshuga 
僕の環境だとloader.gifまだ表示されなかったんですが、佐藤さんの環境では表示されてますか？

2019-06-05 09:18 UTC, akshuga commented
@jrsaruo 
僕の環境では表示されてますね

2019-06-05 09:45 UTC, mosuke commented
@akshuga 
assetsフォルダの位置をローカルでのみ変更したんでしょうか？

2019-06-05 09:50 UTC, akshuga commented
@mosuke 
assetsフォルダの中身をresourcesフォルダに移したので, そのパスに合わせました
もともとの相対パスがずれてて僕の方ではloaderが見えてなかったです

2019-06-05 10:11 UTC, mosuke commented
@akshuga 
> assetsフォルダの中身をresourcesフォルダに移したので, そのパスに合わせました

この変更も反映してもらっていいですか？

2019-06-06 10:19 UTC, mosuke approved these changes

2019-06-06 10:20 UTC, jrsaruo approved these changes

2019-06-06 10:20 UTC, merged