Implemented build-number
RUTILEA/SDTest pull request #18
Opened 2019-06-03 18:44 UTC by dryout

2019-06-04 06:28 UTC, mosuke approved these changes

2019-06-05 08:22 UTC, dryout commented
@mosuke 修正しましたのでレビューお願いします！OKだったらマージお願いしますー

2019-06-05 09:40 UTC, mosuke requested changes
loader.gifの位置が変更されていますが、fbsの仕様に合わせたのでしょうか？

2019-06-06 06:19 UTC, dryout commented
@mosuke 
そうです、もともとそれらのファイルには直接はアクセスされてなかった (.qrc ファイルに埋め込まれている) と思うので動かしても問題ないよね？

2019-06-06 07:14 UTC, mosuke approved these changes

2019-06-06 07:16 UTC, merged