Update learning_model.py
RUTILEA/SDTest pull request #76
Opened 2019-07-13 19:37 UTC by akshuga

## Proposed Changes

  - 閾値の設定を自動で「NGの最大とtest_OKの-3σ点(=0.13パーセント点)」に設定

2019-07-13 19:58 UTC, nwatab requested changes
Replace a comment, *# default threshold FIXME: logic*, with a comment to explain magic number, 0.13.
As it is numpy array, *self.test_results.distances_of_ng_images.max()* is better than standard max

2019-07-16 06:29 UTC, mosuke approved these changes

2019-07-16 10:13 UTC, mosuke commented
@asterisk37n 
change requestedに対応できてるか確認してもらった後にapproveしといてもらえると助かります！

2019-07-16 13:27 UTC, nwatab approved these changes
Good job!

2019-07-16 13:27 UTC, merged